language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: UyGM/gFksa2q28r0G98t9ubNLSdMXrYIK0QbKUX8XKUDry/VHXRBvurAjIAE63QwLISiSTDzl+Hx8opPbdwBmTywsqGIalqArZnIirDvflygQ6Wt2scVWDYiO46P90TngJLYaGZI+UcJKo5opa/RDOqKsAV6q0l52BvGPYM2xz0=
